#!/usr/bin/env bash
#
# VagrantCI - a Poor Man's CI System
# Copyright (C) 2016  Zoff <zoff@zoff.cc>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

# set -x

err_file="/tmp/wait_for_avd.$$.txt"
export err_file
rm -f "$err_file"

wait_until()
{
	# set -x

	counter=2
	export counter

	# echo "+ counter=$counter"
	# echo "+ err_file=$err_file"

	while ! $@
	do
		counter=$[ $counter + 1 ]

		# echo "+- counter=$counter"
		# echo "+- err_file=$err_file"

		if [ $counter -gt 21 ]; then
			touch "$err_file"
			exit 1
		fi
		printf "."
		sleep 30
	done
}

adb_shell_getprop()
{
	# set -x

	adb shell getprop $1 \
	| tr -d ' ' | sed -e 's#\r##'
}

device_ready()
{
	# set -x

	[ "$(adb_shell_getprop init.svc.bootanim)" = "stopped" ]
}

if [ "$1""x" == "wait-for-boot""x" ]; then
	wait_until adb shell true
	res=$?
	if [ $res -ne 0 ]; then
		sleep 60
	fi
	wait_until adb shell true
	res=$?
	if [ $res -ne 0 ]; then
		sleep 60
	fi
	wait_until adb shell true

	wait_until device_ready
	res=$?

	if [ -e "$err_file" ];then
		echo "ERROR: Android Emulator did not start within 10 minutes!"
		rm -f "$err_file"
		exit 1
	else
		exit $res
	fi
fi

